site_name: Hysteria 2

theme:
  name: material
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Light mode
  custom_dir: overrides

  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - search.suggest
    - search.highlight

extra:
  generator: false
  social:
    - icon: fontawesome/solid/circle-dollar-to-slot
      link: https://nowpayments.io/donation?api_key=EJH83FM-FDC40ZW-QGDZRR4-A7SC67S
    - icon: fontawesome/brands/telegram
      link: https://t.me/hysteria_github
    - icon: fontawesome/brands/github
      link: https://github.com/apernet/hysteria

copyright: Copyright © 2020 - 2023 The Hysteria Project

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/apernet/hysteria

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: 简体中文
          build: true
          nav_translations:
            Home: 首页
            Docs: 文档
            Changelog: 更新日志
            GitHub: GitHub
            Donation: 捐赠
            Getting Started: 快速开始
            Installation: 安装
            Server: 服务端
            Client: 客户端
            Advanced: 进阶
            Full Server Config: 完整服务端配置
            Full Client Config: 完整客户端配置
            ACL: ACL
            Traffic Stats API: 流量统计 API
            TProxy: 透明代理
            Port Hopping: 端口跳跃
            Logging: 日志
            Performance: 性能优化
            Troubleshooting: 故障排除
            Misc: 杂项
            What if I hate YAML?: 我不喜欢 YAML 怎么办？
            About HTTP/3: 关于 HTTP/3
            Can I use a CDN?: 可以套 CDN 吗？
            Developers: 开发者
            Build: 构建
            Protocol: 协议
            URI Scheme: URI 格式

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Docs:
      - Getting Started:
          - Installation: docs/getting-started/Installation.md
          - Server: docs/getting-started/Server.md
          - Client: docs/getting-started/Client.md
      - Advanced:
          - Full Server Config: docs/advanced/Full-Server-Config.md
          - Full Client Config: docs/advanced/Full-Client-Config.md
          - ACL: docs/advanced/ACL.md
          - Traffic Stats API: docs/advanced/Traffic-Stats-API.md
          - TProxy: docs/advanced/TPROXY.md
          - Port Hopping: docs/advanced/Port-Hopping.md
          - Logging: docs/advanced/Logging.md
          - Performance: docs/advanced/Performance.md
          - Troubleshooting: docs/advanced/Troubleshooting.md
      - Misc:
          - What if I hate YAML?: docs/misc/Hate-YAML.md
          - About HTTP/3: docs/misc/About-HTTP3.md
          - Can I use a CDN?: docs/misc/CDN.md
          - Hysteria 2 vs 1: docs/misc/2-vs-1.md
      - Developers:
          - Build: docs/developers/Build.md
          - Protocol: docs/developers/Protocol.md
          - URI Scheme: docs/developers/URI-Scheme.md
  - Changelog: docs/Changelog.md
  - GitHub: https://github.com/apernet/hysteria
  - Donation: docs/Donation.md
